sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start createing an image with dockerfile"
 - docker build -t syan1/docker-react-app2 -f Dockerfile.dev .

script:
 - docker  run -e CI=true syan1/docker-react-app2 npm run test -- --coverage

after_success:
 - echo "Test Success"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app2
  env: Dockerreactapp3-env
  bucket_name: elasticbeanstalk-ap-northeast-2-174517951557
  bucket_path: docker-react-app2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY


    
